# Site settings
title: RabbitMQ summit
email: info@rabbitmqsummit.com
name: RabbitMQ Summit Archive
description: >
  Watch lectures from previous years at the RabbitMQ Summit.
  Learn from speakers and keynotes in our video archive.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://archive.rabbitmqsummit.com

twitter:
  username: RabbitMQSummit
author:
    name: RabbitMQSummit
    email: info@rabbitmqsummit.com

# Other
highlighter: rouge # or rouge or null

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    sourcemap: true
    style: compressed
pliugins:
  - jekyll-sitemap
  - jekyll-redirect-from
